---
apiVersion: v1
kind: ConfigMap
data:
  {{- range $key, $value := .Values.variables }}
  {{ $key }}: {{ $value | quote }}
  {{- end}}
metadata:
  name: {{ include "weather-api-servers.fullname" . }}
